dist: bionic
language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_install:
  - sudo apt install g++ build-essential
  - docker build -t vimalpillai1/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vimalpillai1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstaslk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-481611312779"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

