dist: bionic
language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_install:
  - sudo apt install g++ build-essential
  - docker build -t vimalpillai1/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vimalpillai1/docker-react npm run test -- --coverage
